spring.application.name=gameplatform

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=GamePlatformDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=P@ssw0rd

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true