spring.application.name=gameplatform

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=GamePlatformDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=P@ssw0rd

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 上傳檔案大小限制(遊戲檔案、媒體檔案1008)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# 自訂檔案儲存位置
app.upload.game-dir=uploads/games